on:
  pull_request:
    branches: [release]
    types: [closed]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t ${{env.IMAGE_NAME}} .

      - name: Run Docker Image as Container
        run: |
          docker stop dead-lock-client || true
          docker rm ${{ env.IMAGE_NAME }} || true
          docker rmi ${{ env.IMAGE_NAME }} || true
          docker run -d -p 80:3000 ${{env.IMAGE_NAME}}
