on:
  pull_request:
    branches: [release]
    types: [closed]

env:
  IMAGE_NAME: dead-lock-client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker build Image and Push
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ${{secrets.DOCKER_USER}}/${{env.IMAGE_NAME}}:latest --push .

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: |
          sudo docker stop ${{env.IMAGE_NAME}} || true
          sudo docker rm ${{ env.IMAGE_NAME }} || true
          sudo docker rmi ${{ env.IMAGE_NAME }} || true
          sudo docker pull ${{secrets.DOCKER_USER}}/${{env.IMAGE_NAME}}:latest
          sudo docker tag ${{secrets.DOCKER_USER}}/${{env.IMAGE_NAME}}:latest ${{env.IMAGE_NAME}}
          sudo docker run -d -p 80:3000 --name ${{env.IMAGE_NAME}} ${{env.IMAGE_NAME}}
