on:
  pull_request:
    branches: [release]
    types: [closed]

env:
  IMAGE_NAME: dead-lock-client

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          sudo docker buildx build -f Dockerfile -t ${{env.IMAGE_NAME}} .

      - name: Run Docker Image as Container
        run: |
          sudo docker stop dead-lock-client || true
          sudo docker rm ${{ env.IMAGE_NAME }} || true
          sudo docker rmi ${{ env.IMAGE_NAME }} || true
          sudo docker run -d -p 80:3000 ${{env.IMAGE_NAME}}
